#!/usr/bin/env php
<?php
/**
 *
 * CLI tool to quickly test/debug specific API methods.
 *
 */

// composer auto loader
require __DIR__ . '/vendor/autoload.php';

$api = new \Lodestone\Api();

$start = microtime(true);
print_r([
    'results' => $api->character()->get('24085627')
]);
$finish = microtime(true);

echo "duration = ". ($finish - $start) ."ms";
