#!/usr/bin/env php
<?php
/**
 *
 * CLI tool to quickly test/debug specific API methods.
 *
 */

// composer auto loader
require __DIR__ . '/vendor/autoload.php';

$api = new \Lodestone\Api();

print_r([
    'results' => $api->character()->mounts('26707100')
]);
