#!/usr/bin/env php
<?php
/**
 *
 * CLI tool to quickly test/debug specific API methods.
 *
 */

// composer auto loader
require __DIR__ . '/vendor/autoload.php';

$api = new \Lodestone\Api();

$start = microtime(true);

// use async mode
$api->config()->useAsync();

// perform multiple requests
$api->character()->get(730968);
$api->character()->get(15609878);
$api->character()->get(2269193);
$api->character()->get(720399);

// settle responses (they will trigger in the order you added them)
$responses = $api->http()->settle();

$duration = microtime(true) - $start;

print_r([
    $responses,
    "Duration = {$duration}"
]);

