#!/usr/bin/env php
<?php
/**
 *
 * CLI tool to quickly test/debug specific API methods.
 *
 */

// composer auto loader
use Lodestone\Http\AsyncHandler;

require __DIR__ . '/vendor/autoload.php';

$api = new \Lodestone\Api();

$start = microtime(true);

// use async mode
$api->config()->useAsync();

$api->requestId('profile')->character()->get(730968);
$api->requestId('classjobs')->character()->classjobs(730968);
$api->requestId('minions')->character()->minions(730968);
$api->requestId('mounts')->character()->mounts(730968);

$responses = $api->http()->settle();



print_r($responses);

